-- Check for company-related tables in IMS
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
AND (
    TABLE_NAME LIKE '%Company%' OR 
    TABLE_NAME LIKE '%company%' OR
    TABLE_NAME LIKE '%Client%' OR
    TABLE_NAME LIKE '%client%' OR
    TABLE_NAME LIKE '%Office%' OR
    TABLE_NAME LIKE '%office%'
)
ORDER BY TABLE_NAME;

-- Also check for line-related tables
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
AND (
    TABLE_NAME LIKE '%Line%' OR 
    TABLE_NAME LIKE '%line%'
)
ORDER BY TABLE_NAME;

-- And state-related tables
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
AND (
    TABLE_NAME LIKE '%State%' OR 
    TABLE_NAME LIKE '%state%'
)
ORDER BY TABLE_NAME;

-- Check form-related tables
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
AND (
    TABLE_NAME LIKE '%Form%' OR 
    TABLE_NAME LIKE '%form%'
)
ORDER BY TABLE_NAME;