services:
  - type: web
    name: ims-application
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ims_db
          property: connectionString

databases:
  - name: ims_db
    databaseName: IMS_Application
    user: postgres
    plan: free 